# Generated by Django 4.2 on 2023-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("a_id", models.IntegerField(primary_key=True, serialize=False)),
                ("a_createTime", models.DateTimeField(auto_now_add=True)),
                ("a_content", models.TextField()),
                ("a_score", models.IntegerField()),
                ("a_comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                ("as_id", models.IntegerField(primary_key=True, serialize=False)),
                ("as_createTime", models.DateTimeField(auto_now_add=True)),
                ("as_score", models.IntegerField()),
                ("as_answers", models.ManyToManyField(to="questionnaire.answer")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("q_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "q_type",
                    models.CharField(
                        choices=[
                            ("single", "单选"),
                            ("multiple", "多选"),
                            ("judge", "判断"),
                            ("fill", "填空"),
                            ("essay", "解答"),
                            ("grade", "打分"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("q_title", models.TextField()),
                ("q_description", models.TextField()),
                ("q_option_count", models.IntegerField()),
                ("q_options", models.JSONField()),
                ("q_correct_answer", models.TextField()),
                ("q_answers", models.ManyToManyField(to="questionnaire.answer")),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                ("qn_id", models.IntegerField(primary_key=True, serialize=False)),
                ("qn_title", models.TextField()),
                ("qn_description", models.TextField()),
                ("qn_createTime", models.DateTimeField(auto_now_add=True)),
                ("qn_endTime", models.DateTimeField(default=None)),
                (
                    "qn_status",
                    models.CharField(
                        choices=[
                            ("unpublished", "未发布"),
                            ("published", "已发布"),
                            ("closed", "已关闭"),
                        ],
                        default="unpublished",
                        max_length=20,
                    ),
                ),
                ("qn_refillable", models.BooleanField(default=True)),
                ("qn_answers", models.ManyToManyField(to="questionnaire.answersheet")),
                ("qn_questions", models.ManyToManyField(to="questionnaire.question")),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="q_questionnaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="answersheet",
            name="as_questionnaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.questionnaire",
            ),
        ),
    ]
