# Generated by Django 4.2 on 2023-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="as_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="a_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="a_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
