# Generated by Django 4.1.7 on 2023-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_email'),
        ('questionnaire', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a_is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='a_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.visitor'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='as_is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='as_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.visitor'),
        ),
    ]
