# Generated by Django 4.1.7 on 2023-05-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_answer_a_is_user_answer_a_visitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='qn_answers',
            new_name='qn_answersheets',
        ),
    ]
