# Generated by Django 4.1.7 on 2023-05-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_rename_qn_answers_questionnaire_qn_answersheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_status',
            field=models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('closed', '已关闭'), ('banned', '已封禁')], default='unpublished', max_length=20),
        ),
    ]
