# Generated by Django 4.1.7 on 2023-05-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_question_q_score_alter_answer_a_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='a_createTime',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a_is_user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a_user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a_visitor',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='as_is_user',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='as_user',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='as_visitor',
        ),
        migrations.AddField(
            model_name='answer',
            name='a_answersheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.answersheet'),
        ),
    ]
