# Generated by Django 4.1.7 on 2023-05-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_filler_delete_visitor'),
        ('questionnaire', '0006_remove_answer_a_createtime_remove_answer_a_is_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='as_filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.filler'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='as_temporary_save',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
