# Generated by Django 4.1.7 on 2023-05-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_filler_delete_visitor'),
        ('questionnaire', '0007_answersheet_as_filler_answersheet_as_temporary_save_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='as_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='qn_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
