# Generated by Django 4.1.7 on 2023-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_answersheet_as_submitted_questionnaire_qn_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='as_temporary_save',
            field=models.JSONField(default=None),
        ),
    ]
