# Generated by Django 4.1.7 on 2023-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_alter_answersheet_as_temporary_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_manditory',
            field=models.BooleanField(default=False),
        ),
    ]
