# Generated by Django 4.1.7 on 2023-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_question_q_manditory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='as_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
