# Generated by Django 4.2.1 on 2023-05-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_alter_answer_a_id_alter_answersheet_as_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='as_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='as_temporary_save',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_correct_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_option_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_options',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_endTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_title',
            field=models.TextField(null=True),
        ),
    ]
