# Generated by Django 4.2.1 on 2023-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_alter_answer_a_comment_alter_answer_a_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_position',
            field=models.IntegerField(default=0),
        ),
    ]
