# Generated by Django 4.2.1 on 2023-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_question_q_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='qn_data_json',
            field=models.JSONField(default=None, null=True),
        ),
    ]
