# Generated by Django 4.2.1 on 2023-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_questionnaire_qn_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_status',
            field=models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('closed', '已关闭'), ('banned', '已封禁'), ('deleted', '已删除')], default='unpublished', max_length=20),
        ),
    ]
