# Generated by Django 4.2.1 on 2023-05-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_alter_questionnaire_qn_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_manditory',
            new_name='q_mandatory',
        ),
    ]
