# Generated by Django 4.2.1 on 2023-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_rename_q_manditory_question_q_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='qn_publishTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
