# Generated by Django 4.2.1 on 2023-06-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_usertoken_user_usertoken_filler_and_more'),
        ('questionnaire', '0017_questionnaire_qn_publishtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='qn_allowed_users',
            field=models.ManyToManyField(related_name='allowed_users', to='user.user'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='user.user'),
        ),
    ]
