# Generated by Django 4.2.1 on 2023-06-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_questionnaire_qn_allowed_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheet',
            old_name='as_createTime',
            new_name='as_create_time',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='qn_createTime',
            new_name='qn_create_time',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='qn_endTime',
            new_name='qn_end_time',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='qn_publishTime',
            new_name='qn_publish_time',
        ),
    ]
