# Generated by Django 4.2.1 on 2023-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_rename_as_createtime_answersheet_as_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
