# Generated by Django 4.2.1 on 2023-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_alter_question_q_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='qn_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
