# Generated by Django 4.2.1 on 2023-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_alter_questionnaire_qn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_type',
            field=models.CharField(choices=[('normal', '普通问卷'), ('test', '考试问卷'), ('vote', '投票问卷'), ('application', '申请问卷')], default='normal', max_length=20),
        ),
    ]
