# Generated by Django 4.2.1 on 2023-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_alter_questionnaire_qn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_status',
            field=models.CharField(choices=[('unpublished', '未发布'), ('published', '已发布'), ('closed', '已关闭'), ('banned', '已封禁'), ('deleted', '已删除')], default='unpublished', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_type',
            field=models.CharField(choices=[('normal', '普通问卷'), ('test', '考试问卷'), ('vote', '投票问卷'), ('application', '申请问卷')], default='normal', max_length=20, null=True),
        ),
    ]
