# Generated by Django 4.2.1 on 2023-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0024_alter_questionnaire_qn_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='qn_key',
            field=models.TextField(null=True),
        ),
    ]
