# Generated by Django 4.2.1 on 2023-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_alter_questionnaire_qn_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='qn_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
