# Generated by Django 4.2 on 2023-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.IntegerField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=100)),
                ("admin_password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                ("visitor_id", models.IntegerField(primary_key=True, serialize=False)),
                ("visitor_ip", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("user_password", models.CharField(max_length=20)),
                (
                    "user_status",
                    models.CharField(
                        choices=[("free", "未封禁"), ("banned", "封禁")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "user_created_questionnaires",
                    models.ManyToManyField(
                        related_name="created_by_users",
                        to="questionnaire.questionnaire",
                    ),
                ),
                (
                    "user_filled_questionnaires",
                    models.ManyToManyField(
                        related_name="filled_by_users", to="questionnaire.questionnaire"
                    ),
                ),
            ],
        ),
    ]
