# Generated by Django 4.1.7 on 2023-05-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_remove_answer_a_createtime_remove_answer_a_is_user_and_more'),
        ('user', '0002_user_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('filler_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filler_ip', models.CharField(max_length=30)),
                ('filler_is_user', models.BooleanField(default=False)),
                ('filler_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
