# Generated by Django 4.2.1 on 2023-05-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_admin_admin_id_alter_filler_filler_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filler',
            old_name='filler_uid',
            new_name='filler_user',
        ),
    ]
