# Generated by Django 4.2.1 on 2023-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_filler_uid_filler_filler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tel',
            field=models.TextField(null=True),
        ),
    ]
