# Generated by Django 4.2.1 on 2023-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_usertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="expire_time",
            field=models.DateTimeField(),
        ),
    ]
