# Generated by Django 4.2.1 on 2023-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usertoken_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_signature',
            field=models.TextField(null=True),
        ),
    ]
