# Generated by Django 4.2.1 on 2023-05-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.filler'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
