# Generated by Django 4.2.1 on 2023-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_usertoken_user_usertoken_filler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to='avatar/'),
        ),
    ]
