# Generated by Django 4.2.1 on 2023-06-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.admin'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.filler'),
        ),
    ]
