# Generated by Django 4.2.1 on 2023-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_usertoken_admin_alter_usertoken_filler'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_company',
            field=models.TextField(null=True),
        ),
    ]
