name: Deploy to Server

on:
  push:
    branches:
      - main  # 根据你的分支名称进行配置

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy
        run: |
          # 在这里执行你构建和部署的命令
          # 例如：使用Gunicorn启动WSGI服务器
          gunicorn myapp.wsgi:application --bind 0.0.0.0:8000

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: ./
          target: /home/caryz/question_planet
