name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-registry/your-image-name:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh user@server "docker pull your-docker-registry/your-image-name:latest"
            ssh user@server "docker stop your-container-name || true"
            ssh user@server "docker rm your-container-name || true"
            ssh user@server "docker run -d --name your-container-name -p 80:80 your-docker-registry/your-image-name:latest"
